- data/orchestrate/dag_definition.yml
- data/utilities/utilities.meltano.yml
- remove env_aliases
- change from job_id to state-id
> 2.0 migration fixes

- data/transform/models/marts/telemetry/base/unstructured_parsing/context_project.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/schema.yml
Related to https://github.com/meltano/meltano/pull/6552
> account for new context project schema

- .github/workflows/clean_snowflake.yml
- .github/workflows/prod_deploy.yml
- .github/workflows/test.yml
Closes https://github.com/meltano/squared/issues/334
> use commit sha for CI branches

- data/transform/models/marts/telemetry/base/active_projects_base.sql
- data/transform/models/marts/telemetry/daily_active_projects.sql
- data/transform/models/marts/telemetry/project_plugins.sql
Closes https://github.com/meltano/squared/issues/346
> Daily active projects

- README.md
- data/README.md
- data/analyze/README.md
- data/extract/extractors.meltano.yml
- data/extract/mappers.meltano.yml
- data/load/loaders.meltano.yml
- data/orchestrate/README.md
- data/transform/README.md
- data/transform/transformers.meltano.yml
- data/utilities/great_expectations/README.md
- data/utilities/utilities.meltano.yml
Closes https://github.com/meltano/squared/issues/122
- bump tap-slack
- pin to current version all unpinned plugins
- update readmes to point to MeltanoHub for instructions
> bump tap-slack, pin all plugin versions, and update readmes

- data/transform/models/publish/meltano_hub/fact_variant_hub_metrics.sql
Closes https://github.com/meltano/squared/issues/370
> fix bug with hub metrics aggregates

- data/environments/cicd.meltano.yml
- data/extract/extractors.meltano.yml
- data/transform/models/staging/github_search/sources.yml
- data/transform/models/staging/github_search/stg_github_search__pull_requests.sql
- data/transform/models/staging/github_search/stg_github_search__repositories.sql
- add PRs stream
- enable issues
- fix repo duplicate issue. Some urls were showing up twice with different IDs, I suspect because of a create/delete/re-create situation. We only care about the current existing one.
> github search EL

- data/extract/extractors.meltano.yml
Related to https://github.com/meltano/squared/issues/409
> exclude github search forks

- data/transform/models/marts/telemetry/base/active_projects_base.sql
- data/transform/models/marts/telemetry/base/project_base.sql
- data/transform/models/marts/telemetry/fact_cli_executions.sql
- data/transform/models/marts/telemetry/fact_plugin_usage.sql
- data/transform/models/marts/telemetry/project_dim.sql
- data/transform/models/marts/telemetry/schema.yml
Closes https://github.com/meltano/squared/issues/394
> add active cli exec boolean

- data/transform/models/marts/telemetry/fact_cli_executions.sql
- data/transform/models/marts/telemetry/schema.yml
- data/transform/models/marts/telemetry/temp_fact_cli_executions_1d.sql
Closes https://github.com/meltano/internal-data/issues/24
> add monthly pipeline segments

- README.md
as discussed in https://github.com/meltano/internal-marketing/issues/684
> docs: add links and teaser to readme

- data/transform/models/marts/telemetry/base/ip_address_dim.sql
Closes https://github.com/meltano/squared/issues/450
> fix list agg overflow error

- data/extract/extractors.meltano.yml
- data/transform/models/staging/snowplow/stg_snowplow__events.sql
Closes https://github.com/meltano/squared/issues/452
> filter snowplow app_ids for meltano only

- data/transform/models/marts/telemetry/project_funnel_cohort.sql
Closes https://github.com/meltano/internal-data/issues/37.
The major implementation detail to mention here is that I included all of these plugins as getting started guide plugins because they are either in the guides now or were previously:
- tap-github
- tap-gitlab
- target-jsonl
- target-postgres
cc @tayloramurphy
> Getting started funnel level

- data/transform/macros/slack_message_generator.sql
Per suggestion here: https://meltano.slack.com/archives/C0489728QFL/p1667589446383429
> Proposed slack post format update

- data/transform/models/marts/telemetry/fact_cli_executions.sql
Closes https://github.com/meltano/internal-data/issues/44
> bugfix - segmentation using count instead of sum

- data/transform/models/marts/telemetry/fact_cli_executions.sql
Related to https://github.com/meltano/internal-data/issues/40
Adds the fields needed for previous month attributes.
> add previous month segments and pipeline counts

- .github/workflows/clean_snowflake.yml
- .github/workflows/prod_deploy.yml
- .github/workflows/test.yml
- data/ci_get_install_script.py
- data/environments/cicd.meltano.yml
- data/environments/jigsaw.meltano.yml
- data/environments/prod.meltano.yml
- data/environments/staging.meltano.yml
- data/environments/userdev.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/plugins/utilities/dbt-snowflake--dbt-labs.lock
- data/transform/README.md
- data/transform/tests/marts/telemetry/base/assert_structured_exec_pipeline_runs.sql
- data/transform/tests/marts/telemetry/base/assert_structured_pipeline_runs.sql
- data/transform/transformers.meltano.yml
Closes https://github.com/meltano/squared/issues/482
Replaces https://github.com/meltano/squared/pull/411 now that the utility is on meltano hub
FYI @tayloramurphy 
cc @magreenbaum @WillDaSilva - everything looks good to me and tests pass but I wanted to tag you in case you see errors in the cloud project because of some edge case related to this that I couldnt think of.
> exchange dbt transformer for EDK utility

- data/transform/tests/marts/telemetry/base/assert_structured_exec_pipeline_runs.sql
- data/transform/tests/marts/telemetry/base/assert_structured_pipeline_runs.sql
Closes https://github.com/meltano/squared/issues/512
> expand blend test tolerance

- data/transform/models/marts/telemetry/base/hub_logs_parsed.sql
- data/transform/models/marts/telemetry/fact_hub_api_requests.sql
- data/transform/models/marts/telemetry/schema.yml
Closes https://github.com/meltano/squared/issues/108
> Hub logs parsing

- data/environments/cicd.meltano.yml
- data/environments/prod.meltano.yml
- data/environments/staging.meltano.yml
- data/environments/userdev.meltano.yml
- data/extract/extractors.meltano.yml
- data/extract/mappers.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/transform/transformers.meltano.yml
- data/utilities/utilities.meltano.yml
- pin unpinned pip urls
- accept yaml format changes that meltano cli wants to make
> Meltano yaml cleanup

- data/.env.template
- data/environments/cicd.meltano.yml
- data/environments/prod.meltano.yml
- data/environments/staging.meltano.yml
- data/environments/userdev.meltano.yml
- data/extract/extractors.meltano.yml
- data/load/loaders.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/transform/data/team_github_ids.csv
- data/transform/data/team_gitlab_ids.csv
- data/transform/macros/github_activity_slack_message_generator.sql
- data/transform/models/marts/community/contributions.sql
- data/transform/models/publish/slack_notifications/github_activity_notifications.sql
- data/transform/models/staging/github_meltano/stg_github__issues.sql
- data/transform/models/staging/github_meltano/stg_github__pull_requests.sql
- data/transform/models/staging/github_meltano/stg_github__repositories.sql
Closes https://github.com/meltano/squared/issues/479
> GitHub activity slack notifications

- data/transform/models/publish/slack_notifications/slack_alerts.sql
Closes https://github.com/meltano/squared/issues/539
> add repos created to the singer slack messages

- .devcontainer/devcontainer.json
> feat: add devcontainer config

- data/transform/models/marts/telemetry/fact_el_executions.sql
Missing commit that was supposed to be in https://github.com/meltano/squared/pull/576
> bugfix  - add missing commit, remove date filter and add event count

- data/extract/extractors.meltano.yml
This will hopefully resolve an issue were seeing that was fixed by https://github.com/MeltanoLabs/tap-cloudwatch/issues/25.
> bump tap-cloudwatch to 0.3.0

- data/transform/models/marts/telemetry/fact_el_executions.sql
Closes https://github.com/meltano/squared/issues/585
> Fix el pair test

- data/transform/models/marts/telemetry/base/project_base.sql
- data/transform/models/marts/telemetry/base/project_org_mapping.sql
Closes https://github.com/meltano/squared/issues/593
> fix: dedupe orgs and org domains

- CONTRIBUTING.md
- data/CONTRIBUTING.md
- data/environments/userdev.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/transform/transformers.meltano.yml
- data/utilities/snowflake-cloner/.copier-answers.yml
- data/utilities/snowflake-cloner/.gitignore
- data/utilities/snowflake-cloner/README.md
- data/utilities/snowflake-cloner/poetry.lock
- data/utilities/snowflake-cloner/pyproject.toml
- data/utilities/snowflake-cloner/snowflakecloner_ext/__init__.py
- data/utilities/snowflake-cloner/snowflakecloner_ext/extension.py
- data/utilities/snowflake-cloner/snowflakecloner_ext/main.py
- data/utilities/snowflake-cloner/snowflakecloner_ext/pass_through.py
- data/utilities/snowflake-cloner/snowflakecloner_ext/snowflake_wrapper.py
- data/utilities/utilities.meltano.yml
Closes https://github.com/meltano/squared/issues/430
- adds snowflake-cloner extension that clones all prod tables to development schema with proper permissions
- adds contributing docs to explain how to use it
- defaults userdev to use RAW vs personal EL clone
> Snowflake cloner

- data/CONTRIBUTING.md
- data/utilities/snowflake-cloner/snowflakecloner_ext/extension.py
- make sql create or replace for refreshes to work
- remove typo in contributing.md
> snowflake-cloner add create or replace

- data/orchestrate/orchestrators.meltano.yml
@magreenbaum I'll merge this in so the job and schedule exist but I think you need to register it with the cloud Squared project.
> add sample_schedule

- data/transform/models/staging/dynamodb/stg_dynamodb__project_schedules_table.sql
Closes https://github.com/meltano/squared/issues/621
> fix enabled and healthy schedules

- data/extract/extractors.meltano.yml
- data/transform/models/marts/telemetry/base/cloud_executions_base.sql
- data/transform/models/marts/telemetry/base/schema.yml
- data/transform/models/marts/telemetry/cloud_org_dim.sql
- data/transform/models/marts/telemetry/schema.yml
- data/transform/models/staging/dynamodb/schema.yml
- data/transform/models/staging/dynamodb/stg_dynamodb__project_schedules_table.sql
- data/transform/models/staging/dynamodb/stg_dynamodb__projects_table.sql
- data/transform/models/staging/dynamodb/stg_dynamodb__workload_metadata_table.sql
- data/transform/snapshots/meltanohub/snapshot_meltanohub_plugins.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_aws_ips.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_azure_ips.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_gcp_ips.sql
- data/transform/tests/marts/telemetry/assert_cloud_credits_used.sql
- data/transform/tests/staging/dynamodb/assert_project_schedules_parsing.sql
Closes https://github.com/meltano/internal-data/issues/115
> Cloud executions bugfixes

- data/environments/cicd.meltano.yml
- data/environments/prod.meltano.yml
- data/environments/userdev.meltano.yml
- data/extract/extractors.meltano.yml
- data/load/loaders.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/plugins/loaders/target-hubspot--meltanolabs.lock
- data/transform/models/publish/hubspot/org_activity.sql
Closes https://github.com/meltano/internal-data/issues/123
> feat: publish data to hubspot via target-hubspot
