meltano/squared

- data/transform/models/marts/telemetry/project_plugins.sql
Closes https://github.com/meltano/internal-data/issues/1 and https://github.com/meltano/squared/issues/271
Implements the projects x plugin types metric.
- Like I documented in the handbook PR https://github.com/meltano/handbook/pull/286 I thought 14 days was an appropriate look back window. I tried 7 but moving to 14 gave it a 15-20% increase so I wonder if we have users who run pipelines less than once a week that are getting dropped which would make sense comparing to the 28d active number. Again happy to change back if you guys prefer.
- In exploring the difference between the 28d active project counts and this project count, I noticed that the filter were using here to exclude projects that are less than a week old caused the decrease.
- Another difference is that the 28d active …
> Project x plugins

- data/transform/models/marts/telemetry/active_projects_28d.sql
- data/transform/models/marts/telemetry/base/cli_executions_base.sql
Relates to https://github.com/meltano/squared/issues/279
- use new fact_cli_executions model
- use date_dim
- use pipeline pk vs parsing the command
> migrate 28d projects to new models

- .github/workflows/test.yml
- data/extract/extractors.meltano.yml
- data/orchestrate/dag_definition.yml
- data/transform/dbt_project.yml
- data/transform/models/staging/meltanohub/schema.yml
- data/transform/models/staging/meltanohub/sources.yml
- data/transform/models/staging/meltanohub/stg_meltanohub__plugins.sql
Closes https://github.com/meltano/squared/issues/275
- adds tap-meltanohub from https://github.com/pnadolny13/tap-meltanohub but forks from https://github.com/AutoIDM/tap-meltanohub so I might end up using the AutoIDM version if the changes get merged.
- adds CI tests for new tap
- airflow dag schedule
- dbt staging logic
> Hub plugin definitions

- data/transform/models/marts/telemetry/base/environments.sql
- data/transform/models/marts/telemetry/base/hash_lookup.sql
- data/transform/models/marts/telemetry/base/plugin_executions.sql
- data/transform/models/marts/telemetry/base/schema.yml
- data/transform/models/marts/telemetry/base/structured_parsing/struct_plugin_executions.sql
- data/transform/models/marts/telemetry/base/structured_parsing/struct_plugins.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_plugins.sql
- data/transform/models/staging/meltanohub/stg_meltanohub__plugins.sql
Closes https://github.com/meltano/squared/issues/307
- Use only hub definitions for unhashing and leave custom hashed plugins so we can still analyze the hashed version i.e. how many times was that plugin called, by how many projects, etc.
- For structured events where we get the unhashed text, we now hash it ourselves then only unhash if we have the ability to with our hash lookup table sourced from the hub definitions
- Clean up structured plugin types so singer plugins are labeled extractors/loaders/mappers instead of null. This became more important because if we cant unhash the plugin its very helpful to know that its singer/loader vs singer/extractor otherwise its hard to understand anything about the plugin execution.
> Use hub definitions

- .github/workflows/prod_deploy.yml
- data/.gitignore
- data/orchestrate/README.md
- data/orchestrate/dags/meltano.py
- data/transform/models/staging/spreadsheets_anywhere/stg_ssa_aws_ips.sql
- data/transform/models/staging/spreadsheets_anywhere/stg_ssa_azure_ips.sql
- data/transform/models/staging/spreadsheets_anywhere/stg_ssa_gcp_ips.sql
In prod the default airflow dag wasnt working because the airflow containers dont have meltano installed. This fix adds a cache json file with the output of `meltano schedule list --format=json` that gets built during CI and is built into the airflow image. The dag generator is updated to use the file if it exists instead of running a meltano command.
> use a cached schedules file for production

- data/transform/models/marts/telemetry/project_dim.sql
- data/transform/models/marts/telemetry/project_plugins.sql
Closes https://github.com/meltano/squared/issues/345
Previously we assumed a project Id would only have one source but in reality a new project is initialized with a random ID then its explicit moving forward. We now handle that scenario and skip init when finding the project ID source. The first source is taken, ignoring the init source.
> handle multiple project id sources for one ID

- data/extract/extractors.meltano.yml
- data/transform/models/marts/telemetry/fact_cli_executions.sql
- data/transform/models/marts/telemetry/fact_plugin_usage.sql
Closes https://github.com/meltano/squared/issues/371
- IP address join was fanning out executions so tests were failing
- use a start and end range, this means less joins match but its more accurate
- I might end up adjusting the activate date in the snapshots to push it back since they start at the beginning of Aug when really those IP were active prior, we just didnt have a snapshot to track them
> fix ip address join to not duplicate

- data/utilities/snowplow/snowplow_snowcat_snowpipe.sql
- deploy/infrastructure/main.tf
- deploy/infrastructure/s3.tf
- deploy/infrastructure/snowflake.tf
Closes https://github.com/meltano/squared/issues/352 https://github.com/meltano/squared/issues/254
None of these additions are automatically deployed.
- Creates a prod S3 bucket for https://github.com/meltano/squared/issues/352 and https://github.com/meltano/squared/issues/247
- I created the snowflake objects manually but wanted to log an artifact.
- The Terraform changes add an additional SQS notification for files dropped into the "bad" prefix. They get picked up by the Snowpipe thats also created in this PR.
- The bad events were time sensitive for QA so I manually added the notification to the bucket because the infrastructure 
@kgpayne Terraform plan was doing some stuff related to EKS while I was trying to apply my changes. Also I'm looking for a little guidance on how to handle S3 …
> add s3 bucket for squared and pull in manual notification

- .github/workflows/test.yml
- data/environments/cicd.meltano.yml
- data/environments/prod.meltano.yml
- data/environments/userdev.meltano.yml
- data/extract/extractors.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/transform/models/staging/slack/schema.yml
- data/transform/models/staging/slack/sources.yml
- data/transform/models/staging/slack/stg_slack__channels.sql
- data/transform/models/staging/slack/stg_slack__messages.sql
- data/transform/models/staging/slack/stg_slack__threads.sql
closes https://github.com/meltano/squared/issues/395
- The tap only lets you pull private or public channels not a combination so I inherited as 2 different extractors. Leaving the current tap-slack with private messages and a new tap-slack-public for all public channels.
- We dont filter for channels so all are retrieved
- Threads staging came from https://github.com/meltano/squared/pull/377 with the only change being that I added `thread_ts` to the [surrogate key creation](https://github.com/meltano/squared/pull/377/files#diff-00517ca13cdfcf3081d9a76a40043ad51f4ed693b573c028397752c00363cd3bR5). FYI @waynebanksy
- the messages dbt staging model now unions all messages from private and public channels so vs maintaining duplicate staging model logic
- thread look back is set to 7 days for …
> Public slack channels

- data/transform/models/marts/telemetry/base/event_src_activation.md
- data/transform/models/marts/telemetry/base/event_src_activation.sql
- data/transform/models/marts/telemetry/base/schema.yml
- data/transform/tests/marts/telemetry/base/assert_all_unstruct_project_ids_persist.sql
- data/transform/tests/marts/telemetry/base/assert_cli_executions_base_project_ids.sql
Related to https://github.com/meltano/internal-data/issues/26#issuecomment-1254024339
- Fixes the bug
- Adds tests to assert that all project IDs are making it from the raw tables to the base executions tables
- better docs
I tried to do my best to describe what this model is doing in the [dbt docs](https://github.com/meltano/squared/pull/416/files#diff-e8f1c604a4e7a1d02981177533eb862d3b8d3c876300f98fb8423e092f4aea9d).
The goal was originally to get an apples to apples event count comparison between snowplow and GA, then make a decision whether we're getting enough data in Snowplow to start considering it as the primary telemetry source for that project. This is required because historical metrics wont be preserved unless we blend the sources. A challenge with this is that Snowplow gets …
> bugfix: remove filter for structured events for snowplow activation date

- data/transform/models/marts/telemetry/base/cli_executions_base.sql
- data/transform/models/marts/telemetry/base/event_commands_parsed.sql
- data/transform/models/marts/telemetry/schema.yml
The is_exec flag is key to calculating whether a project is active or not. The logic was spread out across struct/unstruct models which is now unnecessary. Clean it up so logic is maintained in 1 place.
> clean up exec event logic

- data/transform/models/marts/telemetry/base/temp_active_projects_base_1d.sql
- data/transform/models/marts/telemetry/fact_cli_executions.sql
- data/transform/models/marts/telemetry/temp_daily_active_projects_1d.sql
- data/transform/models/marts/telemetry/temp_fact_cli_executions_1d.sql
Related to https://github.com/meltano/squared/issues/407
- Adds end of month active flag. Now we can filter for plain active meaning at the time an execution happened, and active at the end of month (EOM). This allows us to excluded projects that might have run something but have since churned, or the opposite where a project becomes active by the end of the month but their execution was between the exploration period <=7d
- Adds a few temporary tables that are simply used for testing the variation of >=1 day active filtering vs the current >=7 day.
cc @tayloramurphy
> add eom active status and 1d filter variation to 7d

- data/transform/macros/compounding_funnel_filters.sql
- data/transform/macros/funnel_filter.sql
- data/transform/models/marts/telemetry/project_funnel_cohort.sql
I was trying to build this in a way where we can reuse the filtering logic with different sets of filters or quickly add to a list. Its not perfect yet though, I'd probably need to pull more of the logic into the macro to remove the dependency on the scaffolding that calls the macro.
I'd say this is a good first iteration though, and it gives us the data we need to build 3 variations of the funnel charts we want - raw/percent of base/percent of parent in funnel
> New project funnels

- data/transform/models/marts/telemetry/project_funnel_cohort.sql
- Added all filters even things like random, so we can fine tune our filtering logic and know where the drop offs are. This was requested during data office hours.
- Add a new filter at the top of the funnel for `NOT_CI_ONLY` where we only ever saw that project in a CI context
- `NOT_NULL_VERSION` filters for null meltano version after '2022-06-01' because new projects would presumably use the newest meltano package version
- Add a separate "attempt" level before add/install and exec so we can tell if theyre successful or not
- `ACTIVE_EXECUTION` added before the final `STILL_ACTIVE` to differentiate projects that are >7 days old but never executed a plugin after their 7 days. This could be simply stopping right at 7 days or if they run non-exec only after their 7 day window so they never …
> Top of funnel filtering

- data/extract/extractors.meltano.yml
- data/transform/models/marts/telemetry/base/hash_lookup.sql
- data/transform/models/marts/telemetry/project_funnel_cohort.sql
I found a few projects that were using multiple meltano versions and if they traversed <2.0 and >2.0 this filter could get confused since it wasnt ordered so I make sure its the version attached to the first event we get from them.
> More precise about first meltano version for funnel filters

- data/transform/tests/marts/telemetry/base/assert_structured_exec_counts.sql
This test asserts that GA has less than or equal to the amount of events in the blended cli base executions table. Installs was failing but it was a very minor amount. I suspect this is from a few blended projects that are using both pre and post 2.0 versions of meltano across their team. We saw enough snowplow events to start preferring them but they still use <2.0 in CI or something to install and its causing a diff. The rest are far bigger in snowplow.
> fix failing event count test, allow <0.5% tolerance

- data/transform/models/publish/slack_notifications/slack_alerts.sql
Closes https://github.com/meltano/squared/issues/464
Use current date unless in CI.
> fix slack notify model not refreshing bug

- data/transform/models/marts/community/singer_contributions.sql
- data/transform/models/publish/slack_notifications/slack_alerts.sql
- add connector type
- allow repos not listed on the hub
- add is_hub_listed flag now that non listed repos are included
- cast boolean nulls to false to be cleaner
- slack alerts still filter for only hub listed activity to avoid noisey non-listed repos
> singer contrib cleanup

- data/transform/models/marts/telemetry/daily_active_projects.sql
Related to https://github.com/meltano/internal-data/issues/36
This adds attributes for end of month. The comparison is now based on the start and end status. If you came in as active and left active, youre unchanged we dont care if you churned then reactivated in the same month if you didnt change status MoM. Additionally if you were added then churned before the end of the month youre unchanged because you change inactive and left inactive.
> add more end of month attributes to daily active projects

- data/load/loaders.meltano.yml
- This issue was fixed https://github.com/caronc/apprise/issues/721 that was the cause of the slack markdown not rendering
- Use a personal fork of target-apprise that pins the apprise commit hash of the fix until the next release
- After the release I'll get it bumped properly in target-apprise (autoidm)
> use target-apprise fork

- data/extract/extractors.meltano.yml
- data/transform/models/marts/community/schema.yml
- data/transform/models/marts/community/singer_contributions.sql
- data/transform/models/marts/telemetry/project_funnel_cohort.sql
Closes https://github.com/meltano/squared/issues/476
- fix failing dbt test related to singer contributions when ownership was transferred and too strict criteria for visibility which can be null in some cases
- add boolean field to singer contributions when github repo was transferred to different owner
- update azure ip spreadsheet url
- use ref for opt outs where it was accidentally hard coding the table reference
> Various bug fixes

- .github/workflows/test.yml
- data/orchestrate/orchestrators.meltano.yml
- deploy/meltano/Dockerfile.meltano
Related to https://meltano.slack.com/archives/C043KMHQ8NN/p1668707781811419?thread_ts=1668703942.507089&cid=C043KMHQ8NN
For deploying to cloud we no longer have the ability to run deps once in the image build process since cloud installs the project into a shell meltano container. In every task we now run deps before any dbt runs. Done at the task level in case cloud ends up parallelizing tasks within a job.
Also noting that the EDK based dbt plugin version would automatically do this for us https://github.com/meltano/squared/pull/411. But for stability sake I preferred to do it this way for now vs replacing the plugin.
> run dbt deps for cloud deployment

- data/transform/models/marts/telemetry/project_funnel_cohort.sql
Closes https://github.com/meltano/squared/issues/477
A few things to note:
- The logic for determining a project's first meltano version slightly changed as part of the move from the funnel model to the more robust implementation in project_dim. It ended up have a very time positive affect (like <5 projects max, mostly no difference or 1 project) where some projects were looking like they had a null meltano version but it wasnt there actual first event. This happens because some projects were also sending legacy structured events around the transistion time near the 2.0 launch so they have null versions and since the structured event timestamps arent as precise so the old logic was treating them as first events when sometimes they werent.
- The meltano version logic change had a positive …
> refactor funnel model to use new project_dim attributes

- data/load/loaders.meltano.yml
Closes https://github.com/meltano/squared/issues/472
- switch back to AutoIDM repo
- bump version since it now uses the new version of apprise that support slack markdown better
> target-apprise back to AutoIDM after version bump

- data/environments/userdev.meltano.yml
- data/transform/macros/slack_message_generator.sql
- data/transform/models/publish/slack_notifications/slack_alerts.sql
We were only including hub listed repos in the alerts previously. Now we include all and add a little melty emoji to signify that its hub listed.
> slack notifications include singer repos

- data/transform/models/marts/telemetry/base/cli_executions_base.sql
- data/transform/models/marts/telemetry/base/project_base.sql
- data/transform/models/marts/telemetry/fact_cli_executions.sql
- data/transform/models/marts/telemetry/fact_plugin_usage.sql
- data/transform/models/marts/telemetry/project_dim.sql
- data/transform/models/marts/telemetry/project_funnel_cohort_codespaces.sql
Related to https://github.com/meltano/internal-data/issues/49. Mostly closes it out but the charts need to be replicated and pointed to this table.
- passes `options_obj` through to be used downstream
- parses out the init project_directory attribute
- uses the directory name to flag known paths like getting started guides and codespace demo
- I couldnt find an obvious way to flow this attribute through to the funnel model so we can toggle in Superset so I had to clone the model and filter for codespace demo projects. There might be a way to do it but right now I'm preaggregating the data to get it in a form that Superset's pivot table likes. We should consider exploring other options if we're going to want the funnels to be more flexible and dynamic.
cc @tayloramurphy @sbalnojan
> Project directory attribute - codespace demo funnel

- data/transform/models/marts/community/slack_members_daily.sql
- data/transform/models/marts/community/slack_new_members.sql
- data/transform/models/staging/slack/stg_slack__users.sql
closes https://github.com/meltano/internal-data/issues/47
A simple first step to limit the use of anything that might be sensitive. I acknowledge that a hash isnt the same as fully encrypting the value but its an easy step to obfuscated from anyone who might be viewing this non-raw data.
NOTE: Once this merges it also requires us to delete those 4 columns from prod tables. Reclone to dev environments.
> add simple hash to slack emails so they dont leave raw

- data/transform/models/marts/telemetry/base/cli_execs_blended.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_unstruct.sql
Closes https://github.com/meltano/squared/issues/512
This was causing the tests to fail because more projects IDs were showing up in the raw tables than in the downstream tables. This is the first month where the dates exceeded the 25 month range.
After re-evaluating since this was implemented we still want all historical data otherwise we miss part of a projects usage attributes if they're outside the 2 year window. For example all their project attributes like total successful pipelines and first event date will get truncated and will always be "today - 25 months".
If we do want to re-implement this to save on query load we should rethink how to do it exactly. Potentially allowing us to filtering projects where their last event exceeds that window. We should still keep them in the …
> stop truncating events older than 2 years

- data/transform/packages.yml
Looks like the git url was still using http instead of ssh.
> use git url for private dbt package

- data/orchestrate/orchestrators.meltano.yml
- data/transform/transformers.meltano.yml
- github el sometimes has rate limiting issues, push meltano el out to the next hour when rate limits reset
- update slack notifications job to refresh dependencies in case it needs to be refreshed manually after data refresh
> move github el out 1 hr and slack refresh all it needs

- deploy/vpn/enroll_client.sh
I ran this as part of https://github.com/meltano/internal-data/issues/59 but it kept exiting early with code 1 even though I had the CLI installed and was logged in. It looks like there an assumption that an env var is present once you've signed in but that doesnt show up in mine, maybe the CLI has changed since this script was written 🤷 . I think this should do what we want, checks to see if the user is logged in once we've confirmed they have the CLI installed.
@WillDaSilva wdyt?
PS: I cancelled the CI jobs because this doesnt change any of the tested `/data` project.
> fix vpn script to not exit early

- data/transform/models/staging/snowplow/schema.yml
- data/transform/models/staging/snowplow/snowplow_bad_parsed.sql
- data/transform/models/staging/snowplow/stg_snowplow__events_bad.sql
- data/transform/profiles/snowflake/profiles.yml
- data/transform/tests/staging/snowplow/structured_events_schema.sql
Closes https://github.com/meltano/squared/issues/257
- reparses an issue where exception context was spelled wrong in 2 meltano releases. I transformed those records to match the expected naming and fed them back into the staging dbt models.
- reparses null exit_events which were valid but the schema was too strict and was later updated.
> Reparse more bad events

- data/transform/models/marts/telemetry/base/cli_execs_blended.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_unstruct.sql
- data/transform/models/staging/snowplow/stg_snowplow__events.sql
2 tests were failing in prod since we added page_view events to snowplow. We werent' explicitly filtering for app_id in the models that do parsing of our custom events. This fixes that.
> filter out non-cli events from custom parsing logic

- .devcontainer/devcontainer.json
This update fixes the `meltano install` command that previously was not working properly.
I've maxed to parallelism 4 to avoid crashing Docker - which happened to me on the first attempt.
> Chore: fix meltano install in devcontainers

- .github/workflows/prod_deploy.yml
- .github/workflows/test.yml
- data/.sqlfluff
- data/environments/cicd.meltano.yml
- data/sqlfluff_file_changes.py
- data/transform/models/common/date_dim.sql
- data/transform/models/marts/telemetry/base/structured_parsing/cmd_parsed_add_remove.sql
- data/transform/models/marts/telemetry/base/structured_parsing/cmd_parsed_elt.sql
- data/transform/models/marts/telemetry/base/structured_parsing/cmd_parsed_run.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_plugins.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/plugin_executions_block.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_plugin_executions.sql
- data/transform/models/marts/telemetry/project_plugins.sql
- data/transform/models/staging/github_search/stg_github_search__issues_base.sql
- data/transform/models/staging/github_search/stg_github_search__pull_requests.sql
- data/transform/models/staging/slack/stg_slack__messages.sql
- data/transform/models/staging/slack/stg_slack__threads.sql
- data/transform/models/staging/slack/stg_slack__users.sql
- data/transform/models/staging/snowplow/stg_snowplow__events.sql
- data/transform/models/staging/snowplow/stg_snowplow__events_bad.sql
- data/transform/snapshots/meltanohub/snapshot_meltanohub_plugins.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_aws_ips.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_azure_ips.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_gcp_ips.sql
- data/utilities/utilities.meltano.yml
- bumps sqlfluff version
- reduces the amount of snowplow data to use
- uses more fine grained default start dates for certain taps to limit data set size
- adds a script that outputs the sql files that have changed so sqlfluff only needs to run against those
> Speed up CI

- data/transform/models/marts/telemetry/base/project_base.sql
- data/transform/models/marts/telemetry/project_dim.sql
Closes https://github.com/meltano/internal-data/issues/80
- adds `persisted_random` for when we think a random project ID source has graduated to an explicit persisted one. This is based on > 7 days old and > 1 IP address
- adds unique IP address count to project dim. It was needed for this and could be helpful to expose in general.
- I created a new project ID source type because it allows us to exclude them if we want to see our original metrics without this change.
Note this will change our primary metrics in the positive direction slightly. See https://github.com/meltano/internal-data/issues/80#issuecomment-1430394074 for details.
cc @tayloramurphy
> add persisted_random for random ids that are long lived

- data/transform/models/marts/telemetry/base/unstructured_parsing/context_cli.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_environment.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_exception.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_identify.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_plugins.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_project.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_block.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_cli.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_exit.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_legacy_with_context.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/event_telemetry_state_change.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_context_flattened.sql
- data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_event_flattened.sql
Closes https://github.com/meltano/squared/issues/524 for now
All of these event and context parsing models were making the downstream models run slow and bottle neck the whole DAG.
- one optimization was to do the joining of events to all contexts in a single table `...context_flattened`. Previously they all got joined individually and unioned together but thats uneccesary and caused extra join overhead. So now each union doesn't have to individually do the joins 5X times, its done once in an upstream table.
- another optimization is to make all the event and context views into tables which doesnt save a lot of query time overall (it actually adds a little bit) for the downstream table since theres only 1 but making them tables allows us it to split the work and parallelize better than 1 …
> Optimize context event parsing

- data/transform/models/marts/telemetry/base/unstructured_parsing/context_base.sql
Closes https://github.com/meltano/squared/issues/569
It looks like the incremental logic was too exact using max timestamp and we likely get some slightly delayed arrival of events. So the max timestamp was higher than we'd want it to be. Instead we use a 1 day look back to make sure all events are caputred.
> accept late arriving events to context_base

- data/orchestrate/orchestrators.meltano.yml
- data/transform/dbt_project.yml
- data/transform/models/marts/telemetry/base/ip_address_dim.sql
- data/transform/models/marts/telemetry/base/project_base.sql
- data/transform/models/marts/telemetry/base/project_org_mapping.sql
- data/transform/models/marts/telemetry/project_dim.sql
- data/transform/models/publish/hubspot/org_activity.sql
- data/transform/models/publish/hubspot/schema.yml
- data/transform/transformers.meltano.yml
Closes https://github.com/meltano/internal-data/issues/82
@tayloramurphy @DouweM heres a sample of what the PR will provide, I improvised a bit. I'm happy to add/remove/edit anything to make it easier to upload. Once this merges I was thinking that I'd make a table chart in superset so anyone on our team can download the newest data as a CSV for upload, until we automate it.
PROJECT_ORG_NAME | PROJECT_ORG_DOMAIN | PROJECT_IDS | PIPELINE_RUNS_L30 | SEGMENTS | ORG_FIRST_EVENT_AT | ORG_LAST_EVENT_AT | ORG_FIRST_ACTIVE_DATE | ORG_LAST_ACTIVE_DATE | IS_CURRENTLY_ACTIVE | UNIQUE_PLUGINS | CURRENT_AS_OF
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Meltano Squared | github.com/meltano/squared | 1 | 63 | MARLIN \|\| GUPPY | 2021-03-05 0:00:00 | 2023-02-14 6:06:30 | 2021-03-19 | …
> Hubspot publish data

- data/extract/extractors.meltano.yml
This issue https://github.com/MeltanoLabs/tap-cloudwatch/issues/15 was resolved in this release, bumping to get the fix.
> bump tap-cloudwatch to 0.2.0

- data/utilities/permifrost/roles.yml
Closes https://github.com/meltano/internal-data/issues/90
@sbalnojan I decided that its probably easier for everyone if I give you access as a normal squared developer. I'll share the credentials with you directly but it limits you from doing anything unsafe, same as my account does. You can CRUD in USERDEV_<X> and CICD_<x> but read-only in raw/prep/prod. This way if you ever want to test or contribute anything in Squared you have the proper access.
> add Sven as snowflake developer

- data/.sqlfluff
- data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_exec_flattened.sql
Previously we were using ARRAY_AGG for rolling up all the options dicts from individual events up to an execution. I realized that this was unnecessary because an execution really only has 1 set of options even though we're sent one with each event (cli start/inflight/complete/exit). By selecting one options dict for the execution it lets us parse the dict much easier later using key lookups vs iterating an array then doing key lookups in each item.
I ended up deciding to get the max length of each dict then chose the largest. I noticed that the last event usually has the most populated options dict with all previous dict data plus any additions but there were a handful of edge cases where legacy events got fired or the event ordering was off for whatever reason so the simplest solutions …
> chose a single options dict for the execution

- data/transform/macros/feature_usage_macro.sql
- data/transform/models/marts/telemetry/base/feature_usage_base.sql
- data/transform/models/marts/telemetry/fact_feature_usage.sql
Closes https://github.com/meltano/squared/issues/530
This is probably just the first iteration for this table. It adds a pattern for tagging executions as using a feature using CTEs and a macro to union all of them together. I'm imagining that once we have a better sense of what we want out of this we can either join/aggregate in different ways to use this:
- **Features as entities:** left join fact_cli_executions to get a feature grain table with all execution attributes.
- This makes it easier to group by all available feature. The feature is the entity like a `fact_feature_execution`.
- Once features are tagged they flow through automatically
- Use cases: generic feature usage over time.
- **Features as attributes:** aggregate all these features up to the single execution
- once …
> Feature tagging

- data/transform/macros/project_funnel.sql
- data/transform/models/marts/telemetry/base/project_base.sql
- data/transform/models/marts/telemetry/project_dim.sql
- data/transform/models/marts/telemetry/project_funnel_cohort.sql
- data/transform/models/marts/telemetry/project_funnel_cohort_codespaces.sql
Closes https://github.com/meltano/internal-data/issues/81
- Adds new filters to is_ephemeral_project_id attribute for excluding certain problem IP hashes and when a projects first execution command included the `--state` flag meaning the project was previously run elsewhere.
- These flow through to all charts and metrics that use the is_ephemeral_project_id attribute for filtering
- In the cohort tables I kept the existing funnel levels but added an addition one that uses the is_ephemeral_project_id attribute to catch any projects not caught by the previous filters. In this case it filter for the `--state` projects and excluded ip hashes. I did this so that we can consistently define what ephemeral is and use it in other places outside the cohort funnels and also keep the current funnel …
> Filter more ephemeral new projects

- data/extract/extractors.meltano.yml
- data/transform/models/marts/telemetry/base/unstructured_parsing/unstruct_exec_flattened.sql
Closes https://github.com/meltano/internal-data/issues/91
This fixes a bug that was causing null options to flow through in some cases. Downstream we're using those options to flag codespaces projects so some/most projects werent getting flagged.
> fix: option object parsing

- data/transform/models/marts/telemetry/cloud_org_dim.sql
- data/transform/models/marts/telemetry/fact_plugin_usage.sql
- implements healthy schedules attribute using the exit code of the previous run
- adds cloud execution ID to plugin usage for zooming in on activity
> Cloud attributes cleanup

- data/orchestrate/orchestrators.meltano.yml
The internal-data repo has CSV files that we want to seed into Snowflake but right now seed is only run on a deployment of squared. That worked in the past but now that theres a new seed source we need to run it daily in case new additions were made to that CSV without manually running a seed on prod or without squared having been deployed recently.
> Run dbt seed daily

- data/transform/models/marts/telemetry/base/project_org_mapping.sql
Closes https://github.com/meltano/internal-data/issues/92
Following https://github.com/meltano/internal-data/pull/117 we have a seed file for mapping org names and domains if we need to override them. This solves a problem where we had subdomains that caused duplicates. For now this is a simple way to override them without having to have complex logic for parsing out subdomains.
> mechanism to manually map org names and domains

- data/transform/snapshots/meltanohub/snapshot_meltanohub_plugins.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_aws_ips.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_azure_ips.sql
- data/transform/snapshots/spreadsheets_anywhere/snapshot_ssa_gcp_ips.sql
In https://github.com/meltano/squared/pull/628 I updated the RANK references to ROW_NUMBER which didnt work the way I expected. The snapshots left very few rows. I noticed because the hub metrics were missing today. 
I'll also need to revert the snapshot changes in production by reverting `dbt_valid_to` updates from this morning.
> revert snapshot use of rownum over rank

- data/extract/extractors.meltano.yml
- data/transform/models/marts/community/singer_contributions.sql
A test was failing in marts_refresh this morning due to null gitlab issue/MR titles ending up in the singer contributions table. Those are puposefully null because they came from the meltano org. I chose to coalesce them.
> fix null singer contrib titles

- data/transform/models/marts/community/singer_repo_dim.sql
I noticed a few gitlab contributions were being counted towards the singer metrics even though they werent actually connector repos. The github search streams are already filtered for repo name matching tap-* and target-* so I added an explicit filter to the gitlab repos query to do the same. This only accounted for ~50 contributions over time. I noticed because the PR/issue counts didnt add up to the total counts split by tap/targets, meaning some werent taps or targets.
> fix: add filter for gitlab projects that arent singer

- data/extract/extractors.meltano.yml
- data/load/loaders.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
- data/plugins/extractors/tap-smoke-test--meltano.lock
- data/plugins/loaders/target-jsonl--andyh1203.lock
Related to https://github.com/meltano/meltano/pull/7758
Its still a draft but if we chose to keep the recommendation of adding a sample schedule, this will allow us to also run that sample schedule and make sure its still functioning as expected on cloud.
> refactor sample_schedule to use smoke test and jsonl from tutorial

- data/transform/models/marts/telemetry/base/cloud_executions_base.sql
- data/transform/models/marts/telemetry/base/cloud_schedule_frequency.sql
- data/transform/models/staging/dynamodb/stg_dynamodb__project_schedules_table.sql
- data/transform/models/staging/dynamodb/stg_dynamodb__projects_table.sql
- data/transform/models/staging/dynamodb/stg_dynamodb__workload_metadata_table.sql
Closes https://github.com/meltano/squared/issues/654
> add more staging columns to dynamo and fix bugs

- .github/workflows/test.yml
- .gitignore
- data/environments/cicd.meltano.yml
- data/extract/extractors.meltano.yml
- data/output/README.md
Closes https://github.com/meltano/squared/issues/604
I configured all pipelines that could support batch to use it. tap-github and tap-dynamodb use stream maps so I couldnt use batch for those.
I will likely revert a few of these after we see them work in CI since theyre somewhat unnecessary for some cases i.e. tap-snowflake for 3 records.
> feat: configure batch pipelines

- data/utilities/permifrost/roles.yml
- adds metronome user that can write to a metronome_integration schema in the raw database
- removes user specific databases and roles that arent used anymore
- remove user asteers from permifrost. Previously already removed from Snowflake manually but the entry still remained here.
> add metronome role and clean up unused roles/users

- data/transform/models/marts/community/schema.yml
- data/transform/models/marts/community/singer_contributions.sql
- data/transform/models/staging/github_search/schema.yml
Closes https://github.com/meltano/squared/issues/664
The same repo can be listed on the hub multiple times i.e. tap-google-analytics and tap-ga4 or the menzenski and meltanolabs variants of tap-mongodb now both refer to meltanolabs. This wasnt handled in the singer contributions model and it was causing one issue or PR to show up multiple times. I fixed this by deduping before joining. The default attribute is now whether the repo is listed as default anywhere on the hub.
While adding a few more uniqueness dbt tests I noticed that there was 1 PR that had the exact same html_url but was 2 distinct github ids. I dont see the second one anywhere on github when I search so I'm guessing that was a bug or was somehow hard deleted. I went ahead and removed that from our data since its bad data …
> fix: duplicate contributions

- data/extract/extractors.meltano.yml
- data/transform/models/marts/telemetry/base/unstructured_parsing/context_base.sql
Closes https://github.com/meltano/squared/issues/673
- update tap snowflake due to bug https://github.com/MeltanoLabs/tap-snowflake/issues/29
- expand context_base look back window by 1 day - I suspect most of these test errors are because some events arent making it into the context base table due to the incremental logic. Hopefully expanding the look back will help in the future. I will also reprocess events from that table back to 7/20/2023 to pull in the missing events
- bump ssa date
> fix: bugs causing failures

- data/transform/models/marts/telemetry/base/unstructured_parsing/context_base.sql
I noticed today that theres still 4 events that didnt get through and which might be causing downstream dbt test failures. The timestamps show that they were created 4-6 days ago but didnt arrive until yesterday so when we look back 1 day for new data they arent considered. I expanded the window to -10 days although this is still imperfect because I see a max of 150 days late (🙄 ) for events in the past, its rare but does happen. We'll likely have to handle them manually when it happens.
Another option could be to add jinja logic to the incremental block to run a full reload once a week/month to fix these types of things. I'll hold off on that for now but might consider it depending on how often this becomes a problem moving forward.
> fix: expand look back window to 10 days for late arriving events

- data/extract/extractors.meltano.yml
- data/orchestrate/orchestrators.meltano.yml
@tayloramurphy I'm reducing the mart refresh schedule to Mon/Weds/Fri to save on snowflake compute since this data is less regularly tracked right now. Theoretically cutting our bill by more than half. Let me know if you think thats appropriate, I can do less or more.
The EL jobs and slack publish feeds will continue to run daily. The slack publish dbt steps use graph operators and very little compute so its lightweight do that every day.
> Refresh mart only mwf

- data/transform/macros/github_activity_slack_message_generator.sql
- data/transform/macros/slack_message_generator.sql
The slack messages werent being generated properly because for some reason github author id and username stopped coming through. Its in the login nested json and when I install the latest version of the tap locally I see those values populated but they arent making it to snowflake for some reason.
> fix: temporarily remove github author names from slack notifications
